const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Spritefont2,
		C3.Behaviors.Fade,
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Behaviors.Persist,
		C3.Behaviors.Physics,
		C3.Behaviors.destroy,
		C3.Plugins.Touch,
		C3.Plugins.Button,
		C3.Behaviors.Platform,
		C3.Behaviors.Timer,
		C3.Behaviors.Tween,
		C3.Plugins.Browser,
		C3.Plugins.Audio,
		C3.Plugins.Date,
		C3.Plugins.Clipboard,
		C3.Plugins.Arr,
		C3.Plugins.TextBox,
		C3.Plugins.TiledBg,
		C3.Plugins.LocalStorage,
		C3.Plugins.Dictionary,
		C3.Plugins.Keyboard,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Button.Acts.SetText,
		C3.Plugins.Spritefont2.Acts.TypewriterText,
		C3.Plugins.Spritefont2.Exps.Text,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.regexreplace,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Spritefont2.Cnds.OnTypewriterTextFinished,
		C3.Behaviors.Fade.Acts.SetFadeInTime,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.Fade.Acts.RestartFade,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.TiledBg.Acts.SetVisible,
		C3.Behaviors.Fade.Acts.SetFadeOutTime,
		C3.Plugins.Dictionary.Acts.AddKey,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.Dictionary.Acts.SetKey,
		C3.Plugins.Arr.Exps.AsJSON,
		C3.Plugins.System.Acts.Signal,
		C3.Behaviors.Timer.Cnds.IsTimerRunning,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.Spritefont2.Cnds.CompareInstanceVar,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.Spritefont2.Acts.SetInstanceVar,
		C3.Plugins.Spritefont2.Acts.Destroy,
		C3.Behaviors.Fade.Acts.SetWaitTime,
		C3.Plugins.Spritefont2.Acts.SetSize,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Plugins.System.Cnds.OnSuspend,
		C3.Plugins.Date.Exps.Now,
		C3.Plugins.System.Cnds.OnResume,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Arr.Cnds.CompareXY,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Dictionary.Exps.Get,
		C3.Plugins.Spritefont2.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Spritefont2.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Cnds.OnSignal,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.Dictionary.Acts.JSONLoad,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Dictionary.Exps.AsJSON,
		C3.Plugins.LocalStorage.Acts.ClearStorage,
		C3.Plugins.Dictionary.Acts.Clear,
		C3.Plugins.System.Cnds.Repeat,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetCollisions
	];
};
self.C3_JsPropNameTable = [
	{Time: 0},
	{Fade: 0},
	{Logo: 0},
	{Sine: 0},
	{Persist: 0},
	{Physics: 0},
	{Planets: 0},
	{ArrayNum: 0},
	{CPSAdded: 0},
	{ClickAdd: 0},
	{PriceMultiplier: 0},
	{Price: 0},
	{ONECpsAdded: 0},
	{PriceDisplay: 0},
	{DestroyOutsideLayout: 0},
	{Coin: 0},
	{TypeText: 0},
	{TypewriterText: 0},
	{Touch: 0},
	{CoinsText: 0},
	{CPSText: 0},
	{Tooltip: 0},
	{ShopBG: 0},
	{Text: 0},
	{Layout: 0},
	{IsShop: 0},
	{ShopTeleport: 0},
	{Shop: 0},
	{IsMinigame: 0},
	{Enabled: 0},
	{LayoutPortal: 0},
	{ClickMultiplier: 0},
	{PriceText: 0},
	{ONECPSadded: 0},
	{ShopButton: 0},
	{Platform: 0},
	{VariableSetter1: 0},
	{Timer: 0},
	{VariableSetter2: 0},
	{AmmountsAdded: 0},
	{Tween: 0},
	{Dummy: 0},
	{Browser: 0},
	{Fullscreen: 0},
	{Audio: 0},
	{Alert: 0},
	{destroyer: 0},
	{CoinTextSpawner: 0},
	{Mute: 0},
	{Planet: 0},
	{ShopNum: 0},
	{PlanetText: 0},
	{CoinAnim: 0},
	{Prestige: 0},
	{UnlockPlanet: 0},
	{LayoutPortal2: 0},
	{AutoCLICKED: 0},
	{Date: 0},
	{imex: 0},
	{download1: 0},
	{Clipboard: 0},
	{array_coinprice: 0},
	{export: 0},
	{import: 0},
	{TextInput: 0},
	{starry_background: 0},
	{LocalStorage: 0},
	{dictsave: 0},
	{PhysCoin: 0},
	{dummyshadow: 0},
	{array_planets: 0},
	{Keyboard: 0},
	{Clickable: 0},
	{Coins: 0},
	{CPS: 0},
	{CoinClickAmmount: 0},
	{OneCPS: 0},
	{PlanetsNum: 0},
	{IsFullscreen: 0},
	{Leaving: 0},
	{Muted: 0},
	{MuteFrame: 0},
	{suspended: 0},
	{unsuspended: 0},
	{FirstShopVisit: 0},
	{DefaultCoin: 0},
	{Typewritten: 0},
	{Checks: 0},
	{clipboard: 0},
	{jsonSaving: 0},
	{Cheat: 0},
	{loadgame: 0},
	{instant: 0},
	{Checks2: 0},
	{DummyAnimation: 0},
	{Multiplier: 0},
	{CoinsAdded: 0},
	{TimeLeft: 0}
];

self.InstanceType = {
	Logo: class extends self.ISpriteFontInstance {},
	Planets: class extends self.ISpriteInstance {},
	Coin: class extends self.ISpriteInstance {},
	TypewriterText: class extends self.ISpriteFontInstance {},
	Touch: class extends self.IInstance {},
	CoinsText: class extends self.ISpriteFontInstance {},
	CPSText: class extends self.ISpriteFontInstance {},
	ShopBG: class extends self.ISpriteInstance {},
	Text: class extends self.ISpriteFontInstance {},
	LayoutPortal: class extends self.ISpriteFontInstance {},
	ShopButton: class extends self.IButtonInstance {},
	VariableSetter1: class extends self.ISpriteInstance {},
	VariableSetter2: class extends self.ISpriteInstance {},
	AmmountsAdded: class extends self.ISpriteFontInstance {},
	Dummy: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	Fullscreen: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Alert: class extends self.ISpriteFontInstance {},
	destroyer: class extends self.ISpriteInstance {},
	CoinTextSpawner: class extends self.ISpriteInstance {},
	Mute: class extends self.ISpriteInstance {},
	Price: class extends self.ISpriteFontInstance {},
	UnlockPlanet: class extends self.ISpriteFontInstance {},
	LayoutPortal2: class extends self.ISpriteFontInstance {},
	AutoCLICKED: class extends self.ISpriteFontInstance {},
	Date: class extends self.IInstance {},
	imex: class extends self.ISpriteInstance {},
	download1: class extends self.IButtonInstance {},
	Clipboard: class extends self.IInstance {},
	array_coinprice: class extends self.IArrayInstance {},
	export: class extends self.ISpriteFontInstance {},
	import: class extends self.ISpriteFontInstance {},
	TextInput: class extends self.ITextInputInstance {},
	starry_background: class extends self.ITiledBackgroundInstance {},
	LocalStorage: class extends self.IInstance {},
	dictsave: class extends self.IDictionaryInstance {},
	PhysCoin: class extends self.ISpriteInstance {},
	dummyshadow: class extends self.ISpriteInstance {},
	array_planets: class extends self.IArrayInstance {},
	Keyboard: class extends self.IInstance {}
}